### PR TITLE
Use download-with-webtorrent-button to download WebTorrent Desktop

### PR DESCRIPTION
**Pull request by wmhilton**
Eh? Eh? Want to make this happen? (artistic mockup below)

image

I can change [download-with-webtorrent-button](https://github.com/wmhilton/download-with-webtorrent-button) however you want to make it work with the webtorrent.io look & feel, etc.

### CODE REVIEW

**Comment by feross** [comment]
@wmhilton This is a cool idea. Would be very impressive to do :)

One thing that we don't want to do is introduce a dependence on external infrastructure (to generate the magnet link). There have been too many issues recently where installer files get replaced, that I prefer to be very, very conservative about how we deliver installer files.

**Comment by wmhilton** [comment]
> One thing that we don't want to do is introduce a dependence on external infrastructure (to generate the magnet link)

Certainly! The automagical webtorrentify.now.sh + cors-buster are just fallbacks and could be completely removed. The ideal would be to generate the magnet link during CI.

**Comment by wmhilton** [comment]
Make creating a .torrent file part of the deployment process, host the torrent file on your website, add `data-webtorrent="latest.win64.torrent"` or something like that to the download link.

**Comment by wmhilton** [comment]
I still think this idea is the bees knees. Here's an updated suggestion for how to do it. Since WebTorrent Desktop is hosted directly on Github via their releases mechanism, we create a `webtorrentify-github-release` tool that creates a `.torrent` file for all the downloads in a Github Release. (E.g. `webtorrent-desktop-v0.18.0.torrent` would contain all the files available for download on https://github.com/webtorrent/webtorrent-desktop/releases/v0.18.0/) Since Github releases are mutable, we can then add that torrent file to the Github release itself. Then on the webtorrent.io webpage, we use something like

```html
<a href="https://github.com/webtorrent/webtorrent-desktop/releases/download/{{version}}/WebTorrentSetup-{{version}}.exe"
   data-webtorrent="https://github.com/webtorrent/webtorrent-desktop/releases/download/{{version}}/index.torrent"
   data-file="WebTorrentSetup-{{version}}.exe">
```

And after adjusting for the inevitable CORS failures, there you have it!

**Comment by DiegoRBaquero** [comment]
I'm gonna drop my comment. Although I think the idea is awesome, I had proposed it myself in the past, I don't think the swarm will ever be large enough to get any advantages, instead we are putting the overhead of the hacky webseed implementation I wrote and webtorrent itself.

Where I could see benefit is in the update system, but that's on Electron. Much pressure could be offloaded if using webtorrent for that.

**Comment by misha-marinenko-official** [comment]
This is great idea

**Comment by alxhotel** [comment]
Closing this pr for now, but feel free to reopen it if needed.

**Pull request closed without merging**
